ccflags-y = -Iinclude/drm
sisvga-y := sisvga_bo.o \
	    sisvga_connector.o \
	    sisvga_crtc.o \
	    sisvga_ddc.o \
	    sisvga_debug.o \
	    sisvga_device.o \
	    sisvga_drv.o \
	    sisvga_encoder.o \
	    sisvga_fbdev.o \
	    sisvga_framebuffer.o \
	    sisvga_modes.o \
	    sisvga_plane.o \
	    sisvga_ttm.o \
	    sisvga_vclk.o

obj-$(CONFIG_DRM_SISVGA)   += sisvga.o
